data_path: data/preprocessed/flour_z_3_impute.csv
oversample: true
model_name: LinearRegressionFlour
scaling_method: none
hyperparameters: {}
test_size: 0.2
random_state: 42
output_path: checkpoints/flour_z_3_impute_lr_none_oversample
