data_path: data/preprocessed/flour_z_2_impute.csv
cross_validation: false
oversample: false
model_name: SVCFlour
scaling_method: standard

test_size: 0.2
random_state: 42
output_path: checkpoints/flour_z_2_impute_svc_standard
