data_path: data/preprocessed/flour_z_2_impute.csv
oversample: true
regression: true
model_name: SVRFlour
scaling_method: standard
hyperparameters: { 'kernel': 'linear', 'C': 1 }
test_size: 0.2
random_state: 42
cross_validation: true
output_path: checkpoints/flour_z_2_impute_svr_standard_oversample_cv
